### PR TITLE
Update imports to support python 3.10

### LINKED ISSUE #50: Not working on python 3.10
Hi,
After installing python 3.10 following error occurred:
ImportError: cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)

### PR DESCRIPTION
**Pull request by albertyw**
`from collections import Mapping` has been deprecated since python 3.3:

```
Python 3.8.10 (default, Sep 28 2021, 16:10:42)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from collections import Mapping
<stdin>:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
```

This fixes imports to make sure flask-sitemap still works on python 3.10+.  Fixes #50 .

### CODE REVIEW

**Comment by pmcl77** [comment]
Will this be merged eventually? I would like to use the extension but cannot... Thanks.
