### ISSUE TITLE
Not working on python 3.10

### ISSUE THREAD

**Issue by mihailangelov** [inveniosoftware/flask-sitemap#50]
Hi,
After installing python 3.10 following error occurred:
ImportError: cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)
